### ISSUE TITLE
/flood_printSettings disconnects you from server.

### ISSUE THREAD

**Issue by ashmaker000** [vulcan-dev/BeamMP-FloodMod#1] opened 2023-02-01 12:32 UTC
Version - 1.0.1

When typing in /flood_printSettings it will disconnect you from the server:

![image](https://user-images.githubusercontent.com/8276382/216043041-7144a9a9-0419-498b-b9c1-c73c8bb6766e.png)

**Comment by daniel-w0** [comment] 2023-02-01 15:16
Hello, I am aware of this.
It's been fixed, I just need to make a new release. The issue is that BeamMP doesn't like the new lines or something, it thinks it's a disconnect code.

**Comment by ashmaker000** [comment] 2023-02-01 15:38
> Hello, I am aware of this. It's been fixed, I just need to make a new release. The issue is that BeamMP doesn't like the new lines or something, it thinks it's a disconnect code.

No worries :), just thought I would note it down

Anywhere to put some feedback?:
Would be good to have a UI like your single player mod or see if you can integrate it into CEI
I'm glad this is a multiplayer mod now so thank you for that just think a UI works better than commands, especially when your playing with friends

**Comment by ashmaker000** [comment] 2023-03-03 12:04
Any update one when a new version will be out as typing /help crashes the server and shuts it down

**Comment by daniel-w0** [comment] 2023-03-03 13:24
> Any update one when a new version will be out as typing /help crashes the server and shuts it down

Sorry, I've been focusing on other stuff. The issue was fixed last month, I've just not posted another release because I decreased the time for the update timer and I'm not 100% sure if it's stable. I've not had time to test it and I don't have a player base to test it.

If you want, just clone the mod, zip it and use that. I don't want to post a release when I'm not sure if it's fully stable.
Also, if you decide to do this then all commands will be different. For example, `flood_setLimitEnabled` will become `flood_limitEnabled`. I changed it because it's shorter

**Comment by ashmaker000** [comment] 2023-03-03 14:35
No problem,
I'll get this cloned and downloaded and test it on a few of my servers and let you know if you want?

**UPDATE**
Just tested on one of my servers and its working better now, also noticed the default speed and speed levels have changed.

**Comment by daniel-w0** [comment] 2024-03-18 22:16
I know, very late reply. But it seems to be working fine with the old chat and the new chat. I'll close this for now, feel free to let me know if you have any other issues

**Closed as completed by daniel-w0** 2024-03-18 22:16 UTC
